force-app/main/default/objects/Opportunity/fields/DatadeInicio__c.field-meta.xml
<CustomField>
    <fullName>DatadeInicio__c</fullName>
    <label>Data de Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TempoEstimado__c.field-meta.xml
<CustomField>
    <fullName>TempoEstimado__c</fullName>
    <label>Tempo Estimado do Projeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorProposta__c.field-meta.xml
<CustomField>
    <fullName>ValorProposta__c</fullName>
    <label>Valor da Proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityPdfController.cls
public class OpportunityPdfController {
    public Opportunity opportunity { get; set; }

    public OpportunityPdfController(ApexPages.StandardController stdController) {
        
        String opportunityId = ApexPages.currentPage().getParameters().get('id');
        this.opportunity = [SELECT Account.Name, DatadeInicio__c, CustoEstimadoProjeto__c, 
                            TempoEstimado__c, ValorProposta__c FROM Opportunity WHERE Id = :opportunityId LIMIT 1];
    }

    public PageReference generatePdf() {
        PageReference pageRef = Page.ContractInfos; 
        pageRef.getParameters().put('id', opportunity.Id); 
        Blob pdfBlob = pageRef.getContentAsPDF();

        
        Attachment attachment = new Attachment();
        attachment.ParentId = opportunity.Id;
        attachment.Name = 'Proposta_' + opportunity.Name + '.pdf';
        attachment.Body = pdfBlob;
        attachment.ContentType = 'application/pdf';
        insert attachment;

        return null;
    }

    public void sendEmail() {
        
        PageReference pageRef = Page.ContractInfos;
        pageRef.getParameters().put('id', opportunity.Id);
        Blob pdfBlob = pageRef.getContentAsPDF();

        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                   
        email.setToAddresses(new String[] { opportunity.Account.Email__c });        
        email.setSubject('Proposta Comercial');
        email.setPlainTextBody('Olá, segue em anexo a proposta comercial.');
        

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName('Proposta_' + opportunity.Name + '.pdf');
        attachment.setBody(pdfBlob);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });

        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
}